### PR TITLE
add support for arcore

### PR DESCRIPTION
**Pull request by dasg34**

### CODE REVIEW

**Comment by woohyun** [comment]
Which ARCore features would be used by applying this patch ?

**Comment by dasg34** [comment]
We can use camera, motion tracking(head tracking) and plane detection.

BTW, ARCore is not currently supported in godot. additional patches are required.

For more information, see https://github.com/GodotVR/godot_arcore.

**Review by woohyun — APPROVED** [review]
LGTM

**Comment by dasg34** [comment]
We have no plans for android support.

**Pull request closed without merging**
